name: Build MacOS App with Nuitka

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Cài đặt các thư viện cần thiết cho tool dubbing của bạn
        pip install nuitka PyQt6 undetected-chromedriver selenium cryptography pyperclip zstandard

    - name: Build with Nuitka
      run: |
        # --include-package: Thay thế cho collect-all để Nuitka nhận diện undetected_chromedriver
        # --macos-create-app-bundle: Tạo file .app chuẩn cho người dùng Mac
        python3 -m nuitka --standalone \
                          --macos-create-app-bundle \
                          --enable-plugin=pyqt6 \
                          --include-package=undetected_chromedriver \
                          --assume-yes-for-downloads \
                          --output-dir=dist \
                          dichmac.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DichMac-MacOS-App
        # Nuitka sẽ xuất file vào dist/dichmac.app
        path: dist/dichmac.app/
